@echo off

:: Gradle start up script for Windows generated by Gradle.



set DIR=%~dp0

set APP_BASE_NAME=%~n0

set APP_HOME=%DIR%



set DEFAULT_JVM_OPTS=-Xmx64m -Xms64m



set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar



if exist "%JAVA_HOME%in\java.exe" goto findJavaFromJavaHome



set JAVA_EXE=java.exe

%JAVA_EXE% -version >NUL 2>&1

if %ERRORLEVEL% == 0 goto init


echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.&goto fail



:findJavaFromJavaHome

set JAVA_HOME=%JAVA_HOME:"=%

set JAVA_EXE=%JAVA_HOME%in\java.exe



if exist "%JAVA_EXE%" goto init


echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%&goto fail



:init

set CMD_LINE_ARGS=

set _SKIP=



:win9xME_args

if not "%@eval[2+2]"=="4" goto execute



:execute

"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%

if %ERRORLEVEL% == 0 goto end



:fail

set EXIT_CODE=%ERRORLEVEL%

if %EXIT_CODE% == 0 set EXIT_CODE=1

exit /b %EXIT_CODE%



:end

exit /b 0

